export enum ProcessStatus {
    ERROR = "ERROR",
    NOT_REQUIRED = "NOT_REQUIRED",
    NOT_STARTED = "NOT_STARTED",
    SCHEDULED = "SCHEDULED",
    RUNNING = "RUNNING",
    CANCELED = "CANCELED",
    FINISHED = "FINISHED",
    SKIPPED = "SKIPPED",
    OUTDATED = "OUTDATED",
}

export enum StageStatus {
    ERROR = "ERROR",
    NOT_STARTED = "NOT_STARTED",
    RUNNING = "RUNNING",
    CANCELED = "CANCELED",
    FINISHED = "FINISHED",
    OUTDATED = "OUTDATED",
}
