configurations:
- index: 0
  name: "Identifier"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 1
  name: "name"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 2
  name: "birthdate"
  type: "DATE"
  scale: "DATE"
  configurations:
  - name: "DateFormatConfiguration"
    dateFormatter: "yyyy-MM-dd"
- index: 3
  name: "death_date"
  type: "DATE"
  scale: "DATE"
  configurations:
  - name: "DateFormatConfiguration"
    dateFormatter: "yyyy-MM-dd"
- index: 4
  name: "Age"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 5
  name: "Sex"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 6
  name: "ChestPainType"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 7
  name: "RestingBP"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 8
  name: "Cholesterol"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 9
  name: "FastingBS"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 10
  name: "RestingECG"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 11
  name: "MaxHR"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 12
  name: "ExerciseAngina"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 13
  name: "Oldpeak"
  type: "DECIMAL"
  scale: "RATIO"
  configurations: []
- index: 14
  name: "ST_Slope"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 15
  name: "HeartDisease"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
