evaluation_configuration:
  data_format: cross-sectional
  resemblance:
    mean: {}
    standard_deviation: {}
    variance: {}
    skewness: {}
    mode: {}
    distinct_values: {}
    fifth_percentile: {}
    median: {}
    q1: {}
    q3: {}
    ninety_fifth_percentile: {}
    kurtosis: {}
    minimum: {}
    maximum: {}
    density: {}
    histogram: {}
    kolmogorov_smirnov: {}
    hellinger_distance: {}
    frequency_plot: {}
    missing_values_count: {}
    missing_values_percentage: {}
  utility:
    machine_learning:
      train_size: 0.8
      random_state: 42
      target_variable: HeartDisease
    discriminator_based_evaluation:
      train_size: 0.8
      random_state: 42
