risk_assessment_configuration:
  singlingout-uni:
    n_attacks: 100
  attribute_inference:
    n_attacks: 100
  linkage:
    n_attacks: 100
    available_columns:
      - Identifier
      - name
      - birthdate
      - death_date
      - Age
      - Sex
    unavailable_columns:
      - ChestPainType
      - RestingBP
      - Cholesterol
      - FastingBS
      - RestingECG
      - MaxHR
      - ExerciseAngina
      - Oldpeak
      - ST_Slope
      - HeartDisease
  data_format: cross-sectional
  train_fraction: 0.8
  targets: []
  n_random_targets: 5
  n_outlier_targets: 5
  n_iterations: 1
  columns_excluded: []
  singlingout-multi:
    n_attacks: 100
  metrics:
    uniqueness: true
