networks:
    data-management-network:
    synthetization-network:
    anonymization-network:
    evaluation-network:

services:
    cinnamon-db:
        image: postgres:16.2-alpine
        container_name: cinnamon-db
        restart: unless-stopped
        networks:
            - data-management-network
        environment:
            # Has to match the datasource settings of the cinnamon-platform container
            - POSTGRES_DB=${PG_DATABASE}
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
#        volumes:
#            - ./volumes/cinnamon-db/data:/var/lib/postgresql/data
    cinnamon-platform:
        image: ghcr.io/ki-aim/cinnamon-platform:latest
        container_name: cinnamon-platform
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:9000:8000"
#        volumes:
#            - ~/.m2:/root/.m2
        networks:
            - data-management-network
            - synthetization-network
            - anonymization-network
            - evaluation-network
        environment:
            CATALINA_OPTS: "-Dserver.tomcat.max-swallow-size=-1 -Dserver.tomcat.max-post-size=${MAX_FILE_SIZE_BYTES:-52428800}"
            CINNAMON_MAX-FILE-SIZE: ${MAX_FILE_SIZE_BYTES:-52428800}

            # Datasource has to match with the configuration of the cinnamon-db container
            SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
            SPRING_DATASOURCE_URL: jdbc:postgresql://cinnamon-db:5432/${PG_DATABASE}
            SPRING.DATASOURCE.USERNAME: ${PG_USERNAME}

            CINNAMON.CORSALLOWEDORIGINS: http://127:0:0:1,http://localhost:4200,http://127.0.0.1:8080

            CINNAMON_IS-DEMO-INSTANCE: ${IS_DEMO_INSTANCE:-false}

            # Anonymization
            CINNAMON.EXTERNAL-SERVER.anonymization-server.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.anonymization-server.URL-SERVER: http://cinnamon-anonymization:8080
            # Synthetization
            CINNAMON.EXTERNAL-SERVER.synthetization-server.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.synthetization-server.URL-SERVER: http://cinnamon-synthetization:5000
            # Evaluation
            CINNAMON.EXTERNAL-SERVER.technical-evaluation-server.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.technical-evaluation-server.URL-SERVER: http://cinnamon-evaluation:5010

            CINNAMON.EXTERNAL-SERVER.risk-assessment-server.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.risk-assessment-server.URL-SERVER: http://cinnamon-risk-assessment:8000
        depends_on:
            - cinnamon-db
        healthcheck:
            test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 20s
    cinnamon-synthetization:
        image: ghcr.io/ki-aim/cinnamon-synthetization:latest
        container_name: cinnamon-synthetization
        restart: unless-stopped
        ports:
            - "127.0.0.1:5000:5000"
        networks:
            - synthetization-network
    cinnamon-evaluation:
        image: ghcr.io/ki-aim/cinnamon-evaluation:latest
        container_name: cinnamon-evaluation
        restart: unless-stopped
        ports:
            - "127.0.0.1:5010:5010"
        networks:
            - evaluation-network
    cinnamon-risk-assessment:
        image: ghcr.io/ki-aim/cinnamon-risk-assessment:latest
        container_name: cinnamon-risk-assessment
        restart: unless-stopped
        ports:
#            - "8000:8000"
            - "127.0.0.1:8000:8000"
        networks:
            - evaluation-network
    cinnamon-anonymization:
        image:  ghcr.io/ki-aim/cinnamon-anonymization:latest
        container_name: cinnamon-anonymization
        restart: unless-stopped
        ports:
            - "127.0.0.1:8081:8080"
            - "127.0.0.1:9001:8000"
        networks:
            - anonymization-network
        environment:
            CATALINA_OPTS: "-Dserver.tomcat.max-swallow-size=-1 -Dserver.tomcat.max-post-size=${MAX_FILE_SIZE_BYTES:-52428800}"
#        volumes:
#            - ~/.m2:/root/.m2
