networks:
    data-management-network:
    synthetization-network:
    anonymization-network:
    evaluation-network:

services:
    ki-aim-db:
        image: postgres:16.2-alpine
        container_name: ki-aim-db
        restart: always
        networks:
            - data-management-network
        environment:
            - POSTGRES_DB=ki_aim_db
            - POSTGRES_USER=ki_aim_user
            - POSTGRES_PASSWORD=changeme
#        volumes:
#            - ./volumes/ki-aim-db/data:/var/lib/postgresql/data
    ki-aim-platform:
        image: ki-aim-platform:0.0.1
        build:
            context: ./
            dockerfile: ./ki-aim-platform/Dockerfile
        container_name: ki-aim-platform
        restart: always
        ports:
#            - "8080:8080"
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:9000:8000"
        volumes:
            - ~/.m2:/root/.m2
        networks:
            - data-management-network
            - synthetization-network
            - anonymization-network
            - evaluation-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ki-aim-db:5432/ki_aim_db
            - KI-AIM.STEPS.SYNTHETIZATION.URL=http://ki-aim-synthetization:5000
            - KI-AIM.STEPS.ANONYMIZATION.URL=http://ki-aim-anon:8080
            - KI-AIM.STEPS.SYNTHETIZATION.CALLBACKHOST=ki-aim-platform
            - KI-AIM.STEPS.ANONYMIZATION.CALLBACKHOST=ki-aim-platform
            - KI-AIM.STEPS.TECHNICAL-EVALUATION.URL=http://ki-aim-evaluation:5010
            - KI-AIM.STEPS.TECHNICAL-EVALUATION.CALLBACKHOST=ki-aim-platform
        depends_on:
            - ki-aim-db
    ki-aim-synthetization:
        image: synthetization_module
        container_name: ki-aim-synthetization
        restart: always
        ports:
#            - "5000:5000"
            - "127.0.0.1:5000:5000"
        networks:
            - synthetization-network
    ki-aim-evaluation:
        image: evaluation_module
        container_name: ki-aim-evaluation
        restart: always
        ports:
#            - "5010:5010"
            - "127.0.0.1:5010:5010"
        networks:
            - evaluation-network
    ki-aim-anon:
        image: ki-aim-anon
        build:
            context: ./
            dockerfile: ./ki-aim-anon/Dockerfile
        container_name: ki-aim-anon
        restart: always
        ports:
            - "127.0.0.1:8081:8080"
            - "127.0.0.1:9001:8000"
        networks:
            - anonymization-network
        volumes:
            - ~/.m2:/root/.m2
