networks:
    data-management-network:
    synthetization-network:
    anonymization-network:
    evaluation-network:

services:
    ki-aim-db:
        image: postgres:16.2-alpine
        container_name: ki-aim-db
        restart: always
        networks:
            - data-management-network
        environment:
            # Has to match the datasource settings of the ki-aim-platform container
            - POSTGRES_DB=ki_aim_db
            - POSTGRES_USER=ki_aim_user
            - POSTGRES_PASSWORD=changeme
#        volumes:
#            - ./volumes/ki-aim-db/data:/var/lib/postgresql/data
    ki-aim-platform:
        image: ki-aim-platform:0.0.1
        build:
            context: ./
            dockerfile: ./ki-aim-platform/Dockerfile
        container_name: ki-aim-platform
        restart: always
        ports:
#            - "8080:8080"
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:9000:8000"
        volumes:
            - ~/.m2:/root/.m2
        networks:
            - data-management-network
            - synthetization-network
            - anonymization-network
            - evaluation-network
        environment:
            # Datasource has to match with the configuration of the ki-aim-db container
            SPRING_DATASOURCE_PASSWORD: changeme
            SPRING_DATASOURCE_URL: jdbc:postgresql://ki-aim-db:5432/ki_aim_db
            SPRING.DATASOURCE.USERNAME: ki_aim_user

            # Anonymization
            KI-AIM.EXTERNAL-SERVER.0.CALLBACK-HOST: ki-aim-platform
            KI-AIM.EXTERNAL-SERVER.0.URL-SERVER: http://ki-aim-anon:8080
            # Synthetization
            KI-AIM.EXTERNAL-SERVER.1.CALLBACK-HOST: ki-aim-platform
            KI-AIM.EXTERNAL-SERVER.1.URL-SERVER: http://ki-aim-synthetization:5000
            # Evaluation
            KI-AIM.EXTERNAL-SERVER.2.CALLBACK-HOST: ki-aim-platform
            KI-AIM.EXTERNAL-SERVER.2.URL-SERVER: http://ki-aim-evaluation:5010

#            KI-AIM.EXTERNAL-SERVER.3.CALLBACK-HOST: ki-aim-platform
#            KI-AIM.EXTERNAL-SERVER.3.URL-SERVER: http://ki-aim-risk-assessment:8000
            KI-AIM.EXTERNAL-SERVER.3.CALLBACK-HOST: localhost
            KI-AIM.EXTERNAL-SERVER.3.URL-SERVER: http://host.docker.internal:8000
        depends_on:
            - ki-aim-db
    ki-aim-synthetization:
        image: synthetization_module
        container_name: ki-aim-synthetization
        restart: always
        ports:
#            - "5000:5000"
            - "127.0.0.1:5000:5000"
        networks:
            - synthetization-network
    ki-aim-evaluation:
        image: evaluation_module
        container_name: ki-aim-evaluation
        restart: always
        ports:
#            - "5010:5010"
            - "127.0.0.1:5010:5010"
        networks:
            - evaluation-network
    ki-aim-risk-assessment:
        image: risk_assessment_module
        container_name: ki-aim-risk-assessment
        restart: always
        ports:
#            - "8000:8000"
            - "127.0.0.1:8000:8000"
        networks:
            - evaluation-network
    ki-aim-anon:
        image: ki-aim-anon
        build:
            context: ./
            dockerfile: ./ki-aim-anon/Dockerfile
        container_name: ki-aim-anon
        restart: always
        ports:
            - "127.0.0.1:8081:8080"
            - "127.0.0.1:9001:8000"
        networks:
            - anonymization-network
        volumes:
            - ~/.m2:/root/.m2
