version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: ki_aim_user
      POSTGRES_DB: ki_aim_db