networks:
    data-management-network:
    synthetization-network:
    anonymization-network:
    evaluation-network:

services:
    cinnamon-db:
        image: postgres:16.2-alpine
        container_name: cinnamon-db
        restart: unless-stopped
        networks:
            - data-management-network
        environment:
            # Has to match the datasource settings of the cinnamon-platform container
            - POSTGRES_DB=cinnamon_db
            - POSTGRES_USER=cinnamon_user
            - POSTGRES_PASSWORD=changeme
#        volumes:
#            - ./volumes/cinnamon-db/data:/var/lib/postgresql/data
    cinnamon-platform:
        image: cinnamon-platform:0.0.1
        build:
            context: ./
            dockerfile: ./cinnamon-platform/Dockerfile
        container_name: cinnamon-platform
        restart: unless-stopped
        ports:
#            - "8080:8080"
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:9000:8000"
        volumes:
            - ~/.m2:/root/.m2
        networks:
            - data-management-network
            - synthetization-network
            - anonymization-network
            - evaluation-network
        environment:
            # Datasource has to match with the configuration of the cinnamon-db container
            SPRING_DATASOURCE_PASSWORD: changeme
            SPRING_DATASOURCE_URL: jdbc:postgresql://cinnamon-db:5432/cinnamon_db
            SPRING.DATASOURCE.USERNAME: cinnamon_user

            # Anonymization
            CINNAMON.EXTERNAL-SERVER.0.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.0.URL-SERVER: http://cinnamon-anonymization:8080
            # Synthetization
            CINNAMON.EXTERNAL-SERVER.1.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.1.URL-SERVER: http://cinnamon-synthetization:5000
            # Evaluation
            CINNAMON.EXTERNAL-SERVER.2.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.2.URL-SERVER: http://cinnamon-evaluation:5010

            CINNAMON.EXTERNAL-SERVER.3.CALLBACK-HOST: cinnamon-platform
            CINNAMON.EXTERNAL-SERVER.3.URL-SERVER: http://cinnamon-risk-assessment:8000
        depends_on:
            - cinnamon-db
    cinnamon-synthetization:
        image: synthetization_module
        container_name: cinnamon-synthetization
        restart: unless-stopped
        ports:
#            - "5000:5000"
            - "127.0.0.1:5000:5000"
        networks:
            - synthetization-network
    cinnamon-evaluation:
        image: evaluation_module
        container_name: cinnamon-evaluation
        restart: unless-stopped
        ports:
#            - "5010:5010"
            - "127.0.0.1:5010:5010"
        networks:
            - evaluation-network
    cinnamon-risk-assessment:
        image: risk_assessment_module
        container_name: cinnamon-risk-assessment
        restart: unless-stopped
        ports:
#            - "8000:8000"
            - "127.0.0.1:8000:8000"
        networks:
            - evaluation-network
    cinnamon-anonymization:
        image: cinnamon-anonymization
        build:
            context: ./
            dockerfile: ./cinnamon-anonymization/Dockerfile
        container_name: cinnamon-anonymization
        restart: unless-stopped
        ports:
            - "127.0.0.1:8081:8080"
            - "127.0.0.1:9001:8000"
        networks:
            - anonymization-network
        volumes:
            - ~/.m2:/root/.m2
