#Second version of anon config for the frontend
anonymization: "anonymization_tabular"
name: "anonymization_tabular"
version: "1.0"
type: "tabular"
display_name: "Anonymization for tabular data."
description: "Anonymization for tabular dataset"
URL: "/api/anonymization/"

configurations:
  modelConfiguration:
      display_name: Privacy Model Configuration
      description: Define the risk threshold, generalization setting and suppression limit which will be used to run the anonymization.
      parameters:
        - name: riskThresholdType
          label: Risk Threshold Type
          type: string
          description: Select the risk threshold type, either 'Max' for e.g. k-Anonymity enforcement or 'Avg' for an average risk threshold.
          default_value: 'Max'
          values: ['Max', 'Avg']
        - name: riskThresholdValue
          label: Risk Threshold Value
          type: float
          description: Select the threshold value based on the risk type. # AP : should we provide an example ?
          default_value: 0.1
          switch:
            - depends_on: riskThresholdType
              conditions:
                - if: Max
                  values: [0.05, 0.075, 0.1, 0.2, 0.5] # KO: added larger values for k=2 and k=5 as well. at least for testing.
                  min_value: 0.05
                  max_value: 0.5
                - if: Avg
                  values: [0.0005, 0.001, 0.005, 0.05, 0.075, 0.1, 0.2, 0.5] # KO: added larger values for k=2 and k=5 as well. at least for testing.
                  min_value: 0.0005
                  max_value: 0.5
        - name: generalizationSetting # AP : should this parameter be kept ?
          label: Generalization Setting
          type: string
          description: Select the generalization setting. # AP : should we provide an example ?
          default_value: 'Global'
          values: [ 'Global', 'Local' ]
        - name: suppressionLimit
          label: Suppression Limit
          type: float
          description: Define the maximum suppression limit (example 0.9).
          default_value: 0
          min_value: 0
          max_value: 1
