evaluation_configuration:
  data_format: cross-sectional
  resemblance:
    mean: {}
    standard_deviation: {}
    variance: {}
    distinct_values: {}
    skewness: {}
    mode: {}
    fifth_percentile: {}
    q1: {}
    median: {}
    q3: {}
    ninety_fifth_percentile: {}
    kurtosis: {}
    minimum: {}
    maximum: {}
    missing_values_count: {} 
    missing_values_percentage: {} 
    frequency_plot: {}
    density: {}
    histogram: {}
