synthetization_configuration:
  algorithm:
    synthesizer: tvae
    type: cross-sectional
    version: "0.1"
    model_parameter:
      embedding_dim: 128
      compress_dims:
        - 128
        - 128
      decompress_dims:
        - 128
        - 128
      l2scale: 0.00005
      loss_factor: 2
      epochs: 300
    model_fitting:
      train: 0.8
    sampling:
      num_samples: 1000
