export enum ProcessStatus {
    NOT_REQUIRED = "NOT_REQUIRED",
    NOT_STARTED = "NOT_STARTED",
    SCHEDULED = "SCHEDULED",
    RUNNING = "RUNNING",
    CANCELED = "CANCELED",
    FINISHED = "FINISHED",
}
