export enum Steps {
	WELCOME,
	UPLOAD,
	DATA_CONFIG,
	VALIDATION,
	VISUALIZATION,
	ANONYMIZATION,
    SYNTHETIZATION,
    EXECUTION,
}

export const StepConfiguration = {
	WELCOME: {
		path: "/start",
		id: "navLinkStart",
		text: "Welcome",
		enum: Steps.WELCOME,
		dependsOn: "",
		index: 0,
	},
	UPLOAD: {
		path: "/upload",
		id: "navLinkUpload",
		text: "Upload data",
		enum: Steps.UPLOAD,
		dependsOn: Steps.WELCOME,
		index: 1,
	},
	DATA_CONFIG: {
		path: "/dataConfiguration",
		id: "navLinkDataConfiguration",
		text: "Data configuration",
		enum: Steps.DATA_CONFIG,
		dependsOn: Steps.UPLOAD,
		index: 2,
	},
	VALIDATION: {
		path: "/dataValidation",
		id: "navLinkDataValidation",
		text: "Data validation",
		enum: Steps.VALIDATION,
		dependsOn: Steps.DATA_CONFIG,
		index: 3,
	},
	VISUALIZATION: {
		path: "/dataVisualization",
		id: "navLinkDataVisualization",
		text: "Data Visualization",
		enum: Steps.VISUALIZATION,
		dependsOn: "",
		index: 4,
	},
	ANONYMIZATION: {
		path: "anonymizationConfiguration",
		id: "navLinkAnonymizationConfiguration",
		text: "Anonymization configuration",
		enum: Steps.ANONYMIZATION,
		dependsOn: Steps.VALIDATION,
		index: 5,
	},
    SYNTHETIZATION: {
        path: "synthetizationConfiguration",
        id: "navLinkSynthetizationConfiguration",
        text: "Synthetization configuration",
        enum: Steps.SYNTHETIZATION,
        dependsOn: Steps.ANONYMIZATION,
        index: 6,
    },
    EXECUTION: {
        path: "execution",
        id: "navLinkExecution",
        text: "Execution",
        enum: Steps.EXECUTION,
        dependsOn: Steps.SYNTHETIZATION,
        index: 7,
    },
};
