export enum Steps {
	WELCOME,
	UPLOAD,
	DATA_CONFIG,
	VALIDATION,
	ANONYMIZATION_CONFIG,
    SYNTHETIZATION_CONFIG,
}

export const StepConfiguration = {
	WELCOME: {
		path: "/start",
		id: "navLinkStart",
		text: "Welcome",
		enum: Steps.WELCOME,
		dependsOn: "",
		index: 0,
	},
	UPLOAD: {
		path: "/upload",
		id: "navLinkUpload",
		text: "Upload data",
		enum: Steps.UPLOAD,
		dependsOn: Steps.WELCOME,
		index: 1,
	},
	DATA_CONFIG: {
		path: "/dataConfiguration",
		id: "navLinkDataConfiguration",
		text: "Data configuration",
		enum: Steps.DATA_CONFIG,
		dependsOn: Steps.UPLOAD,
		index: 2,
	},
	VALIDATION: {
		path: "/dataValidation",
		id: "navLinkDataValidation",
		text: "Data validation",
		enum: Steps.VALIDATION,
		dependsOn: Steps.DATA_CONFIG,
		index: 3,
	},
	ANONYMIZATION_CONFIG: {
		path: "anonymizationConfiguration",
		id: "navLinkAnonymizationConfiguration",
		text: "Anonymization configuration",
		enum: Steps.ANONYMIZATION_CONFIG,
		dependsOn: Steps.VALIDATION,
		index: 4,
	},
    SYNTHETIZATION_CONFIG: {
        path: "synthetizationConfiguration",
        id: "navLinkSynthetizationConfiguration",
        text: "Synthetization configuration",
        enum: Steps.SYNTHETIZATION_CONFIG,
        dependsOn: Steps.ANONYMIZATION_CONFIG,
        index: 5,
    },
	//PERSISTING: {"path": "", "id": "", "text": "", "enum": Steps.PERSISTING, "index": 4},
};
