#Second version of anon config for the frontend
anonymization: "anonymization_tabular"
name: "anonymization_tabular"
version: "1.0"
type: "tabular"
display_name: "Anonymization for tabular data."
description: "Anonymization for tabular dataset"
URL: "/anonymization"

configurations:
  model_configuration:
      display_name: Privacy Model Configuration
      description: Define the risk threshold, generalization setting and suppression limit which will be used to run the anonymization.
      parameters:
        - name: risk_threshold_type
          label: Risk Threshold Type
          type: string
          description: Select the risk threshold type, either 'Max' for e.g. k-Anonymity enforcement or 'Avg' for an average risk threshold.
          default_value: 'Max'
          allowed_values: ['Max', 'Avg']
        - name: risk_threshold_value
          label: Risk Threshold Value
          type: float
          description: Select the threshold value based on the risk type.
          default_value: 0.1
          switch:
            - depends_on: risk_threshold_type
              conditions:
                - if: Max
                  allowed_values: [0.5, 0.2, 0.1, 0.075, 0.05]  # KO: added larger values for k=2 and k=5 as well. at least for testing.
                - if: Avg
                  allowed_values: [0.5, 0.2, 0.1, 0.075, 0.05, 0.005, 0.001, 0.0005] # KO: added larger values for k=2 and k=5 as well. at least for testing.
        - name: generalization_setting
          label: Generalization Setting
          type: string
          description: Select the risk type, either 'Max' or 'Avg'.
          default_value: 'Global'
          allowed_values: [ 'Global', 'Local' ]
        - name: suppression_limit
          label: Suppression Limit
          type: float
          description: Maximum suppression limit.
          default_value: 0
          min_value: 0
          max_value: 1
