synthetization_configuration:
  algorithm:
    synthesizer: arf
    type: cross-sectional
    version: "0.1"
    model_parameter:
      num_trees: 30
      delta: 0
      max_iters: 10
      early_stop: true
      verbose: true
      min_node_size: 5
      device: DEVICE 
      random_state: 0
      sampling_patience: 500
      workspace: workspace
      compress_dataset: false
    model_fitting:
      train: 0.8
    sampling:
      num_samples: 1000
