synthetization_configuration:
  algorithm:
    synthesizer: ctgan
    type: cross-sectional
    version: "0.1"
    model_parameter:
      embedding_dim: 128
      generator_dim:
        - 256
        - 256
        - 256
      discriminator_dim:
        - 256
        - 256
        - 256
      generator_lr: 0.004
      generator_decay: 0.000001
      discriminator_lr: 0.004
      discriminator_decay: 0.000001
      batch_size: 300
      discriminator_steps: 1
      log_frequency: true
      verbose: true
      epochs: 100
      pac: 10
    model_fitting:
      train: 0.8
    sampling:
      num_samples: 1000


