active_profile: heart-automation
profiles:
  - name: heart-local
    mode: single_execution
    cinnamon_url: http://localhost:8080/api
    data_file: "./resources/heart.csv"
    config_file: "./resources/config.yaml"
    result_directory: "./resources"
  - name: fhir-blaze
    mode: single_execution
    cinnamon_url: http://localhost:8080/api
    config_file: "./resources/config-FHIR-server.yaml"
    result_directory: "./resources"
  - name: heart-automation
    mode: directory_execution
    cinnamon_url: http://localhost:8080/api
    source_directory: "./resources/automation"
    config_file: "./resources/config.yaml"
