evaluation_configuration:
  data_format: cross-sectional
  resemblance:
    mean: {}
    standard_deviation: {}
    variance: {}
    distinct_values: {}
    average_text_length: {}
    text_length_fifth_percentile: {}
    text_length_q1: {}
    text_length_median: {}
    text_length_q3: {}
    text_length_ninety_fifth_percentile: {}
    text_length_distribution: {}
    wordcloud: {}
    mode: {}
    fifth_percentile: {}
    q1: {}
    median: {}
    q3: {}
    ninety_fifth_percentile: {}
    minimum: {}
    maximum: {}
    missing_values_count: {} 
    frequency_plot: {}
    density: {}
    histogram: {}
