name: Build and Push Docker Images

on:
  # TODO remove before merging
  pull_request:
  push:
    branches:
      - main

env:
  # Define the registry and images
  REGISTRY: ghcr.io/ki-aim

jobs:
  test:
    permissions:
      checks: write
      pull-requests: write

    uses: ./.github/workflows/run-tests.yml

  build-and-push:
    runs-on: ubuntu-latest

    needs: test

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the code
      - name: Checkout source
        uses: actions/checkout@v3

      # Build all images
      - name: Build Docker images
        run: docker compose -f docker-compose-build.yml build

      # Create an .env file with required parameters
      - name: Create .env file
        run: |
          touch .env
          echo PG_DATABASE="cinnamon_db" >> .env
          echo PG_PASSWORD="etugahjfre" >> .env
          echo PG_USERNAME="cinnamon_user" >> .env
          cat .env

      # Start all containers
      - name: Start all containers
        run: docker compose up -d --wait --wait-timeout=120

      # Check the health of the platform
      - name: Health check
        run: if [[ $(docker inspect --format='{{.State.Health.Status}}' cinnamon-platform) == "healthy"  ]]; then exit 0; else exit 1; fi

      # Stop all containers
      - name: Stop all containers
        run: docker compose down

# TODO activate before merging
      # Login to Docker registry
#      - name: Log in to Docker registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
      # Push the images
#      - name: Push Docker images
#        run: docker compose -f docker-compose-build.yml push
