name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  # Define the registry and images
  REGISTRY: ghcr.io/ki-aim

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the code
      - name: Checkout source
        uses: actions/checkout@v3

      # Login to Docker registry
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Push cinnamon-anonymization
      - name: Build and Push cinnamon-anonymization
        run: |
          docker build -t $REGISTRY/cinnamon-anonymization:latest -f ./cinnamon-anonymization/Dockerfile ./
          docker push $REGISTRY/cinnamon-anonymization:latest

      # Build and Push cinnamon-evaluation
      - name: Build and Push cinnamon-evaluation
        run: |
          docker build -t $REGISTRY/cinnamon-evaluation:latest ./cinnamon-evaluation
          docker push $REGISTRY/cinnamon-evaluation:latest

      # Build and Push cinnamon-platform
      - name: Build and Push cinnamon-platform
        run: |
          docker build -t $REGISTRY/cinnamon-platform:latest -f ./cinnamon-platform/Dockerfile ./
          docker push $REGISTRY/cinnamon-platform:latest

      # Build and Push cinnamon-risk-assessment
      - name: Build and Push cinnamon-anonymization
        run: |
          docker build -t $REGISTRY/cinnamon-risk-assessment:latest ./cinnamon-risk-assessment
          docker push $REGISTRY/cinnamon-risk-assessment:latest

      # Build and Push cinnamon-synthetization
      - name: Build and Push cinnamon-synthetization
        run: |
          docker build -t $REGISTRY/cinnamon-synthetization:latest ./cinnamon-synthetization
          docker push $REGISTRY/cinnamon-synthetization:latest
