name: Python Unittest Workflow

on:
  pull_request:
  push:
    branches:
#      - main
      - 167-automated-tests

jobs:
  test:
    permissions:
      checks: write

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: cinnamon-risk-assessment
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install unittest-xml-reporting

    - name: Run Unittest and Generate Report
      working-directory: cinnamon-risk-assessment
      run: |
        mkdir -p test-results
        python -m xmlrunner discover -s Tests -p "*.py" -o test-results

    - name: Upload Test Results Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: unittest-results
        path: cinnamon-risk-assessment/test-results/
